// This module was automatically generated by node ts-interface-post.ts
// 2026-02-06T10:53:01.285Z

import { CheckerT, createCheckers, ICheckerSuite, ITypeSuite, TType } from 'ts-interface-checker';
import { PostTokenRefresh, Tokens, PostTokenRevoke, AbsoluteTokens } from '../aegapi-auth-types.js';
import exportedTypeSuite from './aegapi-auth-types-ti.js';


// Mapping of type names to types
export interface TypeMap {
    PostTokenRefresh: PostTokenRefresh;
    Tokens: Tokens;
    PostTokenRevoke: PostTokenRevoke;
    AbsoluteTokens: AbsoluteTokens;
}

// Type definitions
export const typeSuite = exportedTypeSuite as ITypeSuite & {
    PostTokenRefresh: TType;
    Tokens: TType;
    PostTokenRevoke: TType;
    AbsoluteTokens: TType;
};

// Checkers
export const checkers = createCheckers(typeSuite) as ICheckerSuite & {
    PostTokenRefresh: CheckerT<PostTokenRefresh>;
    Tokens: CheckerT<Tokens>;
    PostTokenRevoke: CheckerT<PostTokenRevoke>;
    AbsoluteTokens: CheckerT<AbsoluteTokens>;
};

// Export the checkers by default
export default checkers;
