/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PostTokenRefresh = t.iface([], {
  "refreshToken": "string",
});

export const Tokens = t.iface([], {
  "accessToken": "string",
  "expiresIn": "number",
  "tokenType": t.lit('Bearer'),
  "refreshToken": "string",
  "scope": "string",
});

export const PostTokenRevoke = t.iface([], {
  "refreshToken": "string",
});

export const AbsoluteTokens = t.iface([], {
  "accessToken": "string",
  "refreshToken": "string",
  "expiresAt": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  PostTokenRefresh,
  Tokens,
  PostTokenRevoke,
  AbsoluteTokens,
};
export default exportedTypeSuite;
