// This module was automatically generated by node ts-interface-post.ts
// 2026-02-06T10:53:01.287Z

import { CheckerT, createCheckers, ICheckerSuite, ITypeSuite, TType } from 'ts-interface-checker';
import { ApplianceId, ApplianceStatus, ConnectionState, Appliance, Appliances, ApplianceInfoDTO, CapabilityAccess, CapabilityType, CapabilityValue, CapabilityValues, ConditionOperand, ConditionOperator, TriggerCondition, TriggerAction, CapabilityTrigger, ApplianceCapabilityPropertiesBase, ApplianceCapabilityPropertiesNumber, ApplianceCapabilityPropertiesString, ApplianceCapabilityPropertiesCustom, ApplianceCapabilityProperties, ApplianceCapabilities, ApplianceInfo, ApplianceStateProperties, ApplianceState, Command, ErrorResponse } from '../aegapi-types.js';
import exportedTypeSuite from './aegapi-types-ti.js';


// Mapping of type names to types
export interface TypeMap {
    ApplianceId: ApplianceId;
    ApplianceStatus: ApplianceStatus;
    ConnectionState: ConnectionState;
    Appliance: Appliance;
    Appliances: Appliances;
    ApplianceInfoDTO: ApplianceInfoDTO;
    CapabilityAccess: CapabilityAccess;
    CapabilityType: CapabilityType;
    CapabilityValue: CapabilityValue;
    CapabilityValues: CapabilityValues;
    ConditionOperand: ConditionOperand;
    ConditionOperator: ConditionOperator;
    TriggerCondition: TriggerCondition;
    TriggerAction: TriggerAction;
    CapabilityTrigger: CapabilityTrigger;
    ApplianceCapabilityPropertiesBase: ApplianceCapabilityPropertiesBase;
    ApplianceCapabilityPropertiesNumber: ApplianceCapabilityPropertiesNumber;
    ApplianceCapabilityPropertiesString: ApplianceCapabilityPropertiesString;
    ApplianceCapabilityPropertiesCustom: ApplianceCapabilityPropertiesCustom;
    ApplianceCapabilityProperties: ApplianceCapabilityProperties;
    ApplianceCapabilities: ApplianceCapabilities;
    ApplianceInfo: ApplianceInfo;
    ApplianceStateProperties: ApplianceStateProperties;
    ApplianceState: ApplianceState;
    Command: Command;
    ErrorResponse: ErrorResponse;
}

// Type definitions
export const typeSuite = exportedTypeSuite as ITypeSuite & {
    ApplianceId: TType;
    ApplianceStatus: TType;
    ConnectionState: TType;
    Appliance: TType;
    Appliances: TType;
    ApplianceInfoDTO: TType;
    CapabilityAccess: TType;
    CapabilityType: TType;
    CapabilityValue: TType;
    CapabilityValues: TType;
    ConditionOperand: TType;
    ConditionOperator: TType;
    TriggerCondition: TType;
    TriggerAction: TType;
    CapabilityTrigger: TType;
    ApplianceCapabilityPropertiesBase: TType;
    ApplianceCapabilityPropertiesNumber: TType;
    ApplianceCapabilityPropertiesString: TType;
    ApplianceCapabilityPropertiesCustom: TType;
    ApplianceCapabilityProperties: TType;
    ApplianceCapabilities: TType;
    ApplianceInfo: TType;
    ApplianceStateProperties: TType;
    ApplianceState: TType;
    Command: TType;
    ErrorResponse: TType;
};

// Checkers
export const checkers = createCheckers(typeSuite) as ICheckerSuite & {
    ApplianceId: CheckerT<ApplianceId>;
    ApplianceStatus: CheckerT<ApplianceStatus>;
    ConnectionState: CheckerT<ConnectionState>;
    Appliance: CheckerT<Appliance>;
    Appliances: CheckerT<Appliances>;
    ApplianceInfoDTO: CheckerT<ApplianceInfoDTO>;
    CapabilityAccess: CheckerT<CapabilityAccess>;
    CapabilityType: CheckerT<CapabilityType>;
    CapabilityValue: CheckerT<CapabilityValue>;
    CapabilityValues: CheckerT<CapabilityValues>;
    ConditionOperand: CheckerT<ConditionOperand>;
    ConditionOperator: CheckerT<ConditionOperator>;
    TriggerCondition: CheckerT<TriggerCondition>;
    TriggerAction: CheckerT<TriggerAction>;
    CapabilityTrigger: CheckerT<CapabilityTrigger>;
    ApplianceCapabilityPropertiesBase: CheckerT<ApplianceCapabilityPropertiesBase>;
    ApplianceCapabilityPropertiesNumber: CheckerT<ApplianceCapabilityPropertiesNumber>;
    ApplianceCapabilityPropertiesString: CheckerT<ApplianceCapabilityPropertiesString>;
    ApplianceCapabilityPropertiesCustom: CheckerT<ApplianceCapabilityPropertiesCustom>;
    ApplianceCapabilityProperties: CheckerT<ApplianceCapabilityProperties>;
    ApplianceCapabilities: CheckerT<ApplianceCapabilities>;
    ApplianceInfo: CheckerT<ApplianceInfo>;
    ApplianceStateProperties: CheckerT<ApplianceStateProperties>;
    ApplianceState: CheckerT<ApplianceState>;
    Command: CheckerT<Command>;
    ErrorResponse: CheckerT<ErrorResponse>;
};

// Export the checkers by default
export default checkers;
