/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const WeekdayLC = t.union(t.lit('monday'), t.lit('tuesday'), t.lit('wednesday'), t.lit('thursday'), t.lit('friday'), t.lit('saturday'), t.lit('sunday'));

export const RX92PowerMode = t.enumtype({
  "Quiet": 1,
  "Smart": 2,
  "Power": 3,
});

export const RX9BatteryStatus = t.enumtype({
  "Dead": 1,
  "CriticalLow": 2,
  "Low": 3,
  "Medium": 4,
  "High": 5,
  "FullyCharged": 6,
});

export const RX9RobotStatus = t.enumtype({
  "Cleaning": 1,
  "PausedCleaning": 2,
  "SpotCleaning": 3,
  "PausedSpotCleaning": 4,
  "Return": 5,
  "PausedReturn": 6,
  "ReturnForPitstop": 7,
  "PausedReturnForPitstop": 8,
  "Charging": 9,
  "Sleeping": 10,
  "Error": 11,
  "Pitstop": 12,
  "ManualSteering": 13,
  "FirmwareUpgrade": 14,
});

export const RX9Dustbin = t.enumtype({
  "Unknown": "notConnected",
  "Present": "connected",
  "Missing": "empty",
  "Full": "full",
});

export const RX9RoomCategory = t.enumtype({
  "Kitchen": 0,
  "DiningRoom": 1,
  "Hall": 2,
  "LivingRoom": 3,
  "Bedroom": 4,
  "TVRoom": 5,
  "Bathroom": 6,
  "ChildrenRoom": 7,
  "Office": 8,
  "Storage": 9,
  "Other": 10,
});

export const RX9Capabilities = t.union(t.lit('EcoMode'), t.lit('PowerLevels'), t.lit('CustomPlay'), t.lit('FreezeMapOnDemand'), t.lit('InteractiveMap'), t.lit('MultipleScheduledCleaningsPerDay'), t.lit('PowerZones'));

export const RX9CleaningCommand = t.union(t.lit('play'), t.lit('stop'), t.lit('pause'), t.lit('home'));

export const RX9CleaningSessionAction = t.union(t.lit('update'), t.lit('delete'));

export const RX9CleaningSessionMessageType = t.union(t.lit('normal'), t.lit('error'), t.lit('errorRemoved'));

export const RX9CleaningSessionCompletion = t.union(t.lit('abortedByUser'), t.lit('cleaningFinishedSuccessful'), t.lit('cleaningFinishedSuccessfulInCharger'), t.lit('cleaningFinishedSuccessfulInStartPose'), t.lit('endedNotFindingCharger'), t.lit('error'), t.lit('robotPowerDown'));

export const RX9CleaningSessionStartReason = t.union(t.lit('App'), t.lit('Schedule'), t.lit('Ui'));

export const RX9CleaningSessionEndedReason = t.union(t.lit('AbortedByUser'), t.lit('Docked'), t.lit('Nav'), t.lit('Unknown'));

export const RX9CleaningSessionStatus = t.union(t.lit('idle'), t.lit('approaching'), t.lit('started'), t.lit('finished'), t.lit('aborted'), t.lit('terminated'));

export const RX9ZoneStatus = t.enumtype({
  "idle": 1,
  "approaching": 2,
  "started": 3,
  "finished": 4,
  "aborted": 5,
  "terminated": 6,
});

export const RX9CleaningComplete = t.enumtype({
  "incomplete": 0,
  "complete": 1,
});

export const RX9InteractiveMapZoneType = t.union(t.lit('clean'), t.lit('avoid'));

export const RX9CleaningSessionZoneType = t.union(t.lit('cleanZone'), t.lit('avoidZone'));

export const RX9ZoneType = t.enumtype({
  "cleanZone": 0,
  "avoidZone": 1,
});

export const RX9ZoneVertex = t.iface([], {
  "x": "number",
  "y": "number",
});

export const RX9ZoneQuadrilateral = t.tuple("RX9ZoneVertex", "RX9ZoneVertex", "RX9ZoneVertex", "RX9ZoneVertex");

export const RX9MapPoint = t.iface([], {
  "t": "number",
  "xy": t.tuple("number", "number"),
});

export const RX9MapPointAngle = t.iface([], {
  "t": t.opt("number"),
  "xya": t.tuple("number", "number", "number"),
});

export const RX9MapTransform = t.iface([], {
  "t": "number",
  "xya": t.tuple("number", "number", "number"),
});

export const RX9MapZone = t.iface([], {
  "uuid": "string",
  "type": "RX9ZoneType",
  "vertices": t.tuple("RX9MapPoint", "RX9MapPoint", "RX9MapPoint", "RX9MapPoint"),
});

export const RX9MapMatch = t.iface([], {
  "sequenceNo": "number",
  "uuid": "string",
  "zones": t.array("RX9MapZone"),
});

export const RX9MapZoneStatus = t.iface([], {
  "powerMode": "RX92PowerMode",
  "status": "RX9ZoneStatus",
  "uuid": "string",
});

export const RX9MapData = t.iface([], {
  "chargerPoses": t.array("RX9MapPointAngle"),
  "cleaningComplete": "RX9CleaningComplete",
  "crumbCollectionDelta": "boolean",
  "crumbs": t.opt(t.array("RX9MapPoint")),
  "mapMatch": t.opt("RX9MapMatch"),
  "robotPose": "RX9MapPointAngle",
  "robotPoseReliable": "boolean",
  "sessionId": "number",
  "timestamp": "string",
  "transforms": t.array("RX9MapTransform"),
  "zoneStatus": t.opt(t.array("RX9MapZoneStatus")),
});

export const RX92Zone = t.iface([], {
  "goZonesId": t.opt("string"),
  "powerMode": "RX92PowerMode",
});

export const RX92Task = t.iface([], {
  "enabled": "boolean",
  "start": t.iface([], {
    "weekDays": t.array("WeekdayLC"),
    "time": "string",
    "properties": t.iface([], {
      "persistentMapId": t.opt("string"),
      "zones": t.array("RX92Zone"),
    }),
  }),
});

export const RX92Tasks = t.iface([], {
  [t.indexKey]: "RX92Task",
});

export const RX9NoTriggers = t.iface([], {
  [t.indexKey]: "never",
});

export const RX9ApplianceCapabilities = t.iface([], {
  "cleaningCommand": t.iface([], {
    "access": t.lit('readwrite'),
    "type": t.lit('string'),
    "values": t.iface([], {
      "play": "RX9NoTriggers",
      "stop": "RX9NoTriggers",
      "pause": "RX9NoTriggers",
      "home": "RX9NoTriggers",
    }),
  }),
  "robotStatus": t.iface([], {
    "access": t.lit('read'),
    "type": "string",
    "values": t.iface([], {
      "1": "RX9NoTriggers",
      "2": "RX9NoTriggers",
      "3": "RX9NoTriggers",
      "4": "RX9NoTriggers",
      "5": "RX9NoTriggers",
      "6": "RX9NoTriggers",
      "7": "RX9NoTriggers",
      "8": "RX9NoTriggers",
      "9": "RX9NoTriggers",
      "10": "RX9NoTriggers",
      "11": "RX9NoTriggers",
      "12": "RX9NoTriggers",
      "13": "RX9NoTriggers",
      "14": "RX9NoTriggers",
    }),
  }),
  "dustbinStatus": t.opt(t.iface([], {
    "access": t.lit('read'),
    "type": t.lit('string'),
    "values": t.iface([], {
      "notconnected": "RX9NoTriggers",
      "connected": "RX9NoTriggers",
      "empty": "RX9NoTriggers",
      "full": "RX9NoTriggers",
    }),
  })),
  "batteryStatus": t.opt(t.iface([], {
    "access": t.lit('read'),
    "type": t.lit('int'),
    "max": t.lit(6),
    "min": t.lit(1),
  })),
  "powerMode": t.opt(t.iface([], {
    "access": t.union(t.lit('read'), t.lit('readwrite')),
    "type": t.lit('int'),
    "min": t.lit(1),
    "max": t.lit(3),
  })),
  "customPlay/persistentMapId": t.opt(t.iface([], {
    "access": t.lit('readwrite'),
    "type": t.lit('custom'),
  })),
  "customPlay/zones": t.opt(t.iface([], {
    "access": t.lit('readwrite'),
    "type": t.lit('custom'),
  })),
});

export const RX9ApplianceInfo = t.iface([], {
  "applianceInfo": "ApplianceInfoDTO",
  "capabilities": "RX9ApplianceCapabilities",
});

export const RX9Gateway = t.iface([], {
  "connectionId": "string",
  "location": "string",
  "serverId": "string",
});

export const RX9Message = t.iface([], {
  "id": "number",
  "internalErrorId": t.opt("number"),
  "text": "string",
  "timestamp": "number",
  "type": "number",
  "userErrorId": t.opt("number"),
});

export const RX9RobotPushMessage = t.iface([], {
  "time": "string",
  "type": "string",
  "value": "string",
  "information": t.iface([], {
    "id": "string",
    "timestamp": "string",
    "serverInstanceId": "string",
  }),
  "areaCovered": t.union("number", "null"),
});

export const RX9CapabilitySupported = t.iface([], {
  [t.indexKey]: "never",
});

export const RX9CapabilitiesObject = t.iface([], {
  "ecoMode": t.opt("RX9CapabilitySupported"),
  "powerLevels": t.opt("RX9CapabilitySupported"),
  "customPlay": t.opt("RX9CapabilitySupported"),
  "freezeMapOnDemand": t.opt("RX9CapabilitySupported"),
  "interactiveMap": t.opt("RX9CapabilitySupported"),
  "multipleScheduledCleaningsPerDay": t.opt("RX9CapabilitySupported"),
  "powerZones": t.opt("RX9CapabilitySupported"),
});

export const RX9CleaningSessionZone = t.iface([], {
  "id": "string",
  "type": "RX9CleaningSessionZoneType",
  "vertices": "RX9ZoneQuadrilateral",
});

export const RX9CleaningSessionZoneStatus = t.iface([], {
  "id": "string",
  "status": "RX9CleaningSessionStatus",
  "powerMode": "RX92PowerMode",
});

export const RX9CleaningSession = t.iface([], {
  "action": "RX9CleaningSessionAction",
  "areaCovered": t.opt("number"),
  "cleaningDuration": "number",
  "completion": t.opt("RX9CleaningSessionCompletion"),
  "eventTime": "string",
  "id": "string",
  "isTimeReliable": "boolean",
  "lastUpdate": "string",
  "messageType": "RX9CleaningSessionMessageType",
  "persistentMapId": t.opt("string"),
  "persistentMapSN": "number",
  "pitstopCount": "number",
  "pitstopDuration": "number",
  "robotInternalError": t.opt("number"),
  "robotUserError": t.opt("number"),
  "sessionId": "number",
  "startTime": "string",
  "zones": t.opt(t.array("RX9CleaningSessionZone")),
  "zoneStatus": t.opt(t.array("RX9CleaningSessionZoneStatus")),
});

export const RX9CleaningSessionClosedZone = t.iface([], {
  "id": "string",
  "name": "null",
  "type": "RX9ZoneType",
  "vertices": "RX9ZoneQuadrilateral",
});

export const RX9CleaningSessionClosedZoneStatus = t.iface([], {
  "id": "string",
  "status": "RX9ZoneStatus",
  "powerMode": "RX92PowerMode",
});

export const RX9CleaningSessionClosed = t.iface([], {
  "cleanedArea": "number",
  "cleanedAreaId": "string",
  "cleaningDuration": "number",
  "completion": "number",
  "created": "string",
  "endedReason": t.union("RX9CleaningSessionEndedReason", "null"),
  "eventTime": "string",
  "firmwareVersion": "string",
  "id": "number",
  "isChargerPoseReliable": t.union("boolean", "null"),
  "isRobotPoseReliable": t.union("boolean", "null"),
  "isTimeReliable": "boolean",
  "lastUpdate": "string",
  "persistentMapId": t.union("string", "null"),
  "persistentMapSn": "number",
  "pitstopCount": "number",
  "pitstopDuration": "number",
  "platform": "string",
  "robotInternalError": "null",
  "robotUserError": "null",
  "sessionId": "number",
  "startReason": "RX9CleaningSessionStartReason",
  "startTime": "string",
  "zones": t.union(t.array("RX9CleaningSessionClosedZone"), "null"),
  "zoneStatus": t.union(t.array("RX9CleaningSessionClosedZoneStatus"), "null"),
});

export const RX9ApplianceStateReportedBase = t.iface([], {
  "applianceName": "string",
  "availableLanguages": t.array("string"),
  "batteryStatus": "RX9BatteryStatus",
  "capabilities": "RX9CapabilitiesObject",
  "cleaningSession": t.opt("RX9CleaningSession"),
  "cleaningSessionClosed": t.opt("RX9CleaningSessionClosed"),
  "deviceId": t.opt("string"),
  "dustbinStatus": "RX9Dustbin",
  "filter_sqm": t.opt("number"),
  "firmwareVersion": "string",
  "gw": t.opt("RX9Gateway"),
  "language": "string",
  "main_brush_sqm": t.opt("number"),
  "mapData": t.opt("RX9MapData"),
  "messageList": t.iface([], {
    "messages": t.array("RX9Message"),
  }),
  "mute": "boolean",
  "nextFirmwareUpgradeAttempt": t.opt("string"),
  "persistentMapsCreated": t.opt(t.iface([], {
    "mapId": "string",
  })),
  "platform": "string",
  "robotPushMessage": t.opt("RX9RobotPushMessage"),
  "robotStatus": "RX9RobotStatus",
  "side_brush_sqm": t.opt("number"),
});

export const RX91ApplianceStateReported = t.iface(["RX9ApplianceStateReportedBase"], {
  "ecoMode": "boolean",
});

export const RX92ApplianceStateReported = t.iface(["RX9ApplianceStateReportedBase"], {
  "powerMode": "RX92PowerMode",
  "tasks": t.opt("RX92Tasks"),
});

export const RX9ApplianceStateReported = t.union("RX91ApplianceStateReported", "RX92ApplianceStateReported");

export const RX9ApplianceStateProperties = t.iface([], {
  "reported": "RX9ApplianceStateReported",
});

export const RX9ApplianceState = t.iface([], {
  "applianceId": "ApplianceId",
  "connectionState": "ConnectionState",
  "status": "ApplianceStatus",
  "properties": "RX9ApplianceStateProperties",
});

export const RX9InteractiveMapZone = t.iface([], {
  "name": "string",
  "id": "string",
  "zoneType": "RX9InteractiveMapZoneType",
  "vertices": "RX9ZoneQuadrilateral",
  "roomCategory": "RX9RoomCategory",
  "powerMode": t.union("RX92PowerMode", t.lit(0), "null"),
});

export const RX9InteractiveMap = t.iface([], {
  "name": "string",
  "id": "string",
  "timestamp": "string",
  "rotation": "number",
  "zones": t.union(t.array("RX9InteractiveMapZone"), "null"),
});

export const RX9InteractiveMaps = t.array("RX9InteractiveMap");

export const RX9CommandCleaning = t.iface([], {
  "CleaningCommand": "RX9CleaningCommand",
});

export const RX9CommandCustomPlayZone = t.iface([], {
  "zoneId": "string",
  "powerMode": "RX92PowerMode",
});

export const RX9CustomPlayMapZones = t.iface([], {
  "persistentMapId": "string",
  "zones": t.array("RX9CommandCustomPlayZone"),
});

export const RX9CommandCustomPlay = t.iface([], {
  "CustomPlay": "RX9CustomPlayMapZones",
});

export const RX9Command = t.union("RX9CommandCleaning", "RX9CommandCustomPlay");

const exportedTypeSuite: t.ITypeSuite = {
  WeekdayLC,
  RX92PowerMode,
  RX9BatteryStatus,
  RX9RobotStatus,
  RX9Dustbin,
  RX9RoomCategory,
  RX9Capabilities,
  RX9CleaningCommand,
  RX9CleaningSessionAction,
  RX9CleaningSessionMessageType,
  RX9CleaningSessionCompletion,
  RX9CleaningSessionStartReason,
  RX9CleaningSessionEndedReason,
  RX9CleaningSessionStatus,
  RX9ZoneStatus,
  RX9CleaningComplete,
  RX9InteractiveMapZoneType,
  RX9CleaningSessionZoneType,
  RX9ZoneType,
  RX9ZoneVertex,
  RX9ZoneQuadrilateral,
  RX9MapPoint,
  RX9MapPointAngle,
  RX9MapTransform,
  RX9MapZone,
  RX9MapMatch,
  RX9MapZoneStatus,
  RX9MapData,
  RX92Zone,
  RX92Task,
  RX92Tasks,
  RX9NoTriggers,
  RX9ApplianceCapabilities,
  RX9ApplianceInfo,
  RX9Gateway,
  RX9Message,
  RX9RobotPushMessage,
  RX9CapabilitySupported,
  RX9CapabilitiesObject,
  RX9CleaningSessionZone,
  RX9CleaningSessionZoneStatus,
  RX9CleaningSession,
  RX9CleaningSessionClosedZone,
  RX9CleaningSessionClosedZoneStatus,
  RX9CleaningSessionClosed,
  RX9ApplianceStateReportedBase,
  RX91ApplianceStateReported,
  RX92ApplianceStateReported,
  RX9ApplianceStateReported,
  RX9ApplianceStateProperties,
  RX9ApplianceState,
  RX9InteractiveMapZone,
  RX9InteractiveMap,
  RX9InteractiveMaps,
  RX9CommandCleaning,
  RX9CommandCustomPlayZone,
  RX9CustomPlayMapZones,
  RX9CommandCustomPlay,
  RX9Command,
};
export default exportedTypeSuite;
